site_name: "" 
theme: 
    palette:
        scheme: slate
        primary: white
    logo: /img/favicon.png
    name: material
    custom_dir: custom_theme/
repo_url: https://github.com/factionsecurity/faction
